# Generated by Django 3.0.7 on 2020-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_profile', models.ImageField(upload_to='pics')),
                ('s_name', models.CharField(max_length=50)),
                ('s_pass', models.CharField(max_length=20)),
                ('s_branch', models.CharField(max_length=5)),
                ('s_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_name', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('sub_id', models.CharField(max_length=10)),
                ('upload_file', models.FileField(upload_to='downloads')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_profile', models.ImageField(upload_to='pics')),
                ('t_name', models.CharField(max_length=50)),
                ('t_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('sub_id', models.CharField(max_length=10)),
                ('upload_file', models.FileField(upload_to='downloads')),
            ],
        ),
    ]
